name       : piksemel
version    : 1.3.1
release    : 4
source     :
    - https://getsol.us/sources/piksemel-1.3.1.tar.xz : ab73f5a6077e773464e0cf4c6076b475d757c12f273e40304264b7637c165fff
license    : GPL-3.0-or-later
component  : system.base
summary    : Python XML API based on the iksemel library
description: |
    Python XML API based on the iksemel library.
build      : |
    %python_setup
install    : |
    %python_install
